@startuml

    namespace net.zarski.conference.ci.plantshop {

        class ShoppingCart {
            +ShoppingCart()
            +size(): int
        }

        class Session {
            +Session()
            +put(String, Object): void
            +get(String): Object
        }

        class Shop {
            +Shop(String)
            +getShopName(): String
            {static} +main(String...): void
        }
    }

    net.zarski.conference.ci.plantshop.Shop --> net.zarski.conference.ci.plantshop.Session: currentSession

@enduml
