@startuml

    namespace net.zarski.conference.ci.plantshop {

        class Store {
            +Store(String)
            +getShopName(): String
            {static} +main(String...): void
        }

        class ShoppingCart {
            +ShoppingCart()
            +size(): int
        }

        class Session {
            +Session()
            +put(String, Object): void
            +get(String): Object
        }
    }

    net.zarski.conference.ci.plantshop.Store --> net.zarski.conference.ci.plantshop.Session: currentSession

@enduml
