@startuml

    namespace net.zarski.conference.ci.plantshop {
        class Shop {
            +Shop(String)
            +getShopName(): String
            +getCurrentSession(): Session
            {static} +main(String...): void
        }
    }

@enduml
