site_name: plant-shop

# Meta tags (placed in header)
site_description: 
site_author: Wojciech Zarski
#site_url:

# Repository (add link to repository on each page)
repo_name: plant-shop
repo_url: http://github.com/sratatata/plant-shop
#edit_uri: edit/master/src/doc

#Copyright (shown at the footer)
#copyright: 'Copyright &copy; 2017 Your Name'

# Meterial theme
theme: 'material'
#extra:
#  palette:
#    primary: 'indigo'
#    accent: 'indigo'

#  social:
#    - type: 'github'
#      link: 'https://github.com/you'
#    - type: 'twitter'
#      link: 'https://twitter.com/you'


# Google Analytics
#google_analytics:
#  - 'UA-111111111-1'
#  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences

